'use client'
import type { Metadata } from 'next'
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import { ReactNode, useEffect } from 'react'
import '@/asset/theme/theme.scss'
import CreatePortalLayout from '@/component/layout/CreatePortal.layout'
import GlobalSearchData from '@/feature/GlobalSearchData'
import { ProgressProvider } from '@bprogress/next/app'

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{
    children: ReactNode
}>) {
    useEffect(() => {
        // Load Bootstrap JS only on client
        // @ts-ignore
        import('bootstrap/dist/js/bootstrap.bundle.min')
    }, [])
    return (
        <html lang="en" className="">
            <head>
                <link rel="icon" href="/favicon-tlt.png" sizes="any" />
            </head>
            <body>
                <ProgressProvider
                    height="4px"
                    color="#138F8F"
                    options={{ showSpinner: false }}
                    shallowRouting>
                    {children}

                    {/*<CreatePortalLayout>*/}
                    <GlobalSearchData />
                    {/*</CreatePortalLayout>*/}
                </ProgressProvider>
            </body>
        </html>
    )
}
